### ISSUE TITLE
Notification über Änderung im Knoten-Status

### ISSUE THREAD

**Issue by okin** [freifunk-darmstadt/ffda-jarvis#5]
Wäre es nicht interessant zu sehen wenn Knoten online bzw. offline gehen?
Dazu könnte man noch mitteilen wie lange der Knoten online / offline war.

**Comment by mweinelt** [comment]
Das resultiert vermutlich in einer Menge von Bot-Traffic. Schau dir mal #ffin oderf #ffka an, die haben es mit diesen Notifications noch bunter getrieben.

**Comment by andir** [comment]
Wir haben das mittlerweile in #ffda-log mit  https://github.com/freifunk-darmstadt/knotenbot umgesetzt.
